#!/usr/bin/env node
/**
 * build-lookup.mjs
 *
 * Reads manifest.json + chunks/index.json, packs the lookup table into a flat
 * byte array, and writes it as a hex string to stdout or a file.
 *
 * Usage:
 *   node scripts/build-lookup.mjs                        # hex to stdout
 *   node scripts/build-lookup.mjs --out hex.txt          # hex to file
 *   node scripts/build-lookup.mjs --solidity             # .sol constant snippet
 */

import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const HANDOFF = join(__dirname, "..", "images", "handoff");

const manifest = JSON.parse(readFileSync(join(HANDOFF, "manifest.json"), "utf8"));
const index = JSON.parse(readFileSync(join(HANDOFF, "chunks", "index.json"), "utf8"));

// ── Build the packed lookup table ──────────────────────────────────────────
//
// Layout (total ~1,979 bytes):
//   336 × 5 bytes   record data  (3B chunk<<24 | localOffset, 2B length)
//   271 × 1 byte    shape index per trait
//    8  × 3 bytes   chunk global starts

const records = index; // 336 records in order: shapes 0..63, palettes 0..270, compat

// Compute chunk global starts from the records.
// Shapes are the first 64 records; the first shape of each chunk tells us the chunk start.
const chunkStarts = new Array(8).fill(0);
const chunkSeen = new Set();
for (const rec of records) {
  if (!chunkSeen.has(rec.chunk)) {
    chunkStarts[rec.chunk] = rec.off; // first record's local offset = 0 for each chunk
    chunkSeen.add(rec.chunk);
  }
}

// Actually chunk starts are simpler: chunk 0 starts at 0, chunk 1 starts at the
// end of chunk 0, etc. We derive them from the chunk sizes.
// The chunk files are sequential in the concatenated data.
// We need cumulative offsets. Let's compute from the records directly.
{
  // Find the max (off + len) for each chunk to determine where the next chunk starts.
  const chunkEnds = new Array(8).fill(0);
  for (const rec of records) {
    const end = rec.off + rec.len;
    if (end > chunkEnds[rec.chunk]) chunkEnds[rec.chunk] = end;
  }
  // Chunk starts are cumulative sums of chunk ends.
  let cumulative = 0;
  for (let i = 0; i < 8; i++) {
    chunkStarts[i] = cumulative;
    cumulative += chunkEnds[i];
  }
}

const buf = [];
const writeU8 = (v) => buf.push(v & 0xff);
const writeU16BE = (v) => { buf.push((v >> 8) & 0xff); buf.push(v & 0xff); };
const writeU24BE = (v) => { buf.push((v >> 16) & 0xff); buf.push((v >> 8) & 0xff); buf.push(v & 0xff); };

// 1. Records (336 × 5 bytes)
//    Offset is 3 bytes: high byte = chunk index, low 2 bytes = local offset
//    (all local offsets are < 65,536). Pack as chunk<<16 | off so the 3-byte
//    big-endian write emits [chunk, off>>8, off&0xff].
for (const rec of records) {
  const packed = (rec.chunk << 16) | rec.off;
  writeU24BE(packed);
  writeU16BE(rec.len);
}

// 2. Shape indices per trait (271 × 1 byte)
for (let i = 0; i < 271; i++) {
  writeU8(manifest.traits[i].shape);
}

// 3. Chunk starts (8 × 3 bytes)
for (let i = 0; i < 8; i++) {
  writeU24BE(chunkStarts[i]);
}

const hex = buf.map((b) => b.toString(16).padStart(2, "0")).join("");

// ── Output ─────────────────────────────────────────────────────────────────

const solidiySnippet = `
// Auto-generated by scripts/build-lookup.mjs — DO NOT EDIT
bytes constant LOOKUP_TABLE = hex"${hex}";
`.trim();

const args = process.argv.slice(2);
if (args.includes("--solidity")) {
  const outPath = args[args.indexOf("--solidity") + 1] || "lookup-table.sol";
  writeFileSync(outPath, solidiySnippet);
  console.error(`Wrote Solidity snippet to ${outPath}`);
} else if (args.includes("--out")) {
  const outPath = args[args.indexOf("--out") + 1] || "hex.txt";
  writeFileSync(outPath, hex);
  console.error(`Wrote hex to ${outPath}`);
} else {
  console.log(hex);
}

console.error(`Lookup table: ${buf.length} bytes, ${records.length} records, ${manifest.traits.length} traits`);
console.error(`Chunk starts: [${chunkStarts.join(", ")}]`);
